"""Generate the KaTeX metric tables the math text face lays out from.

KaTeX lays out from a metric table baked into its bundle: per face and code point,
``[depth, height, italic, skew, width]`` in em. The math text face draws Latin letters
and digits from the reading face instead of the KaTeX faces, so for those code points
the baked table no longer describes the glyphs on screen, and it also keeps KaTeX's
Greek at a size that reads small beside PT Serif.

This tool rebuilds the six affected tables: swapped code points are re-measured from the
reading face's own outlines, Greek is scaled by a frozen per-face factor, and everything
else is carried over from KaTeX unchanged. It does that twice, once per composite: for
``KPress Math Text``, which draws from PT Serif, and for ``KPress Math Text Sans``, which
draws from Source Sans 3 in the sans roles and the sans reading face. The result is
written to ``static/katex/katex-text-metrics.js`` as ``globalThis.kpressKatexTextMetrics``
-- the serif set as the object's own face keys, the sans set nested under ``sans``, and
the original tables under ``katex`` for per-node opt-outs. ``katex-math-runtime.js``
installs the appropriate set per rendered node with
``katex.__setFontMetrics``, which replaces a face's whole table and has no getter, so
each table must be complete.

Run ``python -m devtools.katex_text_metrics`` to regenerate the asset, ``--check`` to
verify the shipped copy still matches its inputs, and ``--print-scale`` to print the
Greek scale factors the composite's ``size-adjust`` descriptors must equal.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Any, Final, cast

from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont

ROOT: Final = Path(__file__).resolve().parents[1]
STATIC: Final = ROOT / "src" / "kpress" / "format" / "static"
KATEX_BUNDLE: Final = STATIC / "katex" / "katex.min.js"
ASSET_PATH: Final = STATIC / "katex" / "katex-text-metrics.js"
FACE_CSS_PATH: Final = STATIC / "katex" / "katex-text-face.css"
READING_FONTS: Final = STATIC / "fonts"
KATEX_FONTS: Final = STATIC / "katex" / "fonts"

REGENERATE_COMMAND: Final = "uv run python -m devtools.katex_text_metrics"

# Public JS contract, mirrored by katex-math-runtime.js and the tests.
GLOBAL_NAME: Final = "kpressKatexTextMetrics"
SCALE_KEY: Final = "scale"
#: The nested table set for the sans composite. The serif set is the object's own face
#: keys, so the two never collide: a KaTeX face name is capitalized and hyphenated.
SANS_KEY: Final = "sans"
KATEX_KEY: Final = "katex"
ASSET_HEADER: Final = (
    "/* GENERATED by devtools/katex_text_metrics.py — do not edit. Complete KaTeX metric"
    " tables for the faces the math text face swaps; applied by katex-math-runtime.js through"
    " katex.__setFontMetrics. */"
)

# KaTeX rounds its own table to five decimals, so five keeps the carried-over entries
# byte-identical to what the bundle ships and gives the re-measured ones the same
# resolution.
PRECISION: Final = 5

# Code points the composite family draws from the reading face.
DIGITS: Final = tuple(range(0x30, 0x3A))
LETTERS: Final = (*range(0x41, 0x5B), *range(0x61, 0x7B))
LETTERS_AND_DIGITS: Final = (*DIGITS, *LETTERS)

# Code points the Greek scale factor multiplies. The upright faces carry capitals only;
# the italic faces carry the lowercase alphabet and its variants as well.
UPRIGHT_GREEK: Final = tuple(range(0x391, 0x3AA))
ITALIC_GREEK: Final = tuple(range(0x370, 0x400))

# ---- Greek scale factors ----
#
# The reading face has no Greek, so KaTeX keeps it, and left alone it sits visibly small
# beside PT Serif. Each affected face is therefore scaled to the reading face's own
# vertical measure -- italic Greek to its x-height, upright capitals to its cap height --
# and every metric value in the Greek ranges is multiplied by the same factor so KaTeX
# lays out what the browser draws.
#
# Derived once from OS/2, rounded to three decimals, and frozen here as literals because
# the `size-adjust` descriptors in katex-text-face.css must equal them exactly. Nothing
# recomputes them at run time: `--print-scale` prints them, and `--check` re-derives them
# from the fonts and fails if a font bump has moved one.
#
#   face             reading face (per 1000 em)     KaTeX face                factor
#   Main-Regular     PT Serif cap 700             /  KaTeX_Main-Regular 683    1.025
#   Main-Bold        PT Serif cap 700             /  KaTeX_Main-Bold 686       1.020
#   Math-Italic      PT Serif Italic x 507        /  KaTeX_Math-Italic 441     1.150
#   Math-BoldItalic  PT Serif Bold Italic x 509   /  KaTeX_Math-BoldItalic 452 1.126
#   Main-Italic      as Math-Italic: `\mathit` is laid out from this table, but the
#                    composite's italic slot draws its Greek with KaTeX_Math-Italic,
#                    so both the Greek rows and the factor come from the face that
#                    is drawn (`greek_source_face`)                        1.150
#   Main-BoldItalic  as Math-BoldItalic, for the same reason                1.126
#
# KaTeX_Math-BoldItalic is the one face whose OS/2 sxHeight is not its x-height: the
# table says 532 while every lowercase glyph in the face tops out at 452, and 532 would
# shrink the Greek instead of growing it. `_vertical_measure` cross-checks OS/2 against
# the ink height of the reference glyph and prefers the ink when the two disagree by more
# than OS2_INK_TOLERANCE, which is where 452 comes from.
MAIN_REGULAR_SCALE: Final = 1.025
MAIN_BOLD_SCALE: Final = 1.020
MATH_ITALIC_SCALE: Final = 1.150
MATH_BOLD_ITALIC_SCALE: Final = 1.126

# Ink-versus-OS/2 disagreement, in em, past which the ink height wins.
#
# The value has to separate four measured cases in the faces this tool reads, so it is
# not a round number picked for comfort:
#
#   0.080  KaTeX_Math-BoldItalic's sxHeight: 532 declared against a 452 ink `x`. A
#          declared value that is simply not the face's x-height, and the reason this
#          fallback exists at all.
#   0.007  Source Sans 3's sCapHeight at wght 650: 660 declared against a 653 ink `H`.
#   0.004  the same at wght 400: 660 declared against a 656 ink `H`. Source Sans varies
#          its sxHeight along the weight axis, and the drawn x-height tracks it to the
#          unit, but it does not vary sCapHeight. 660 is drawn only at the fvar default
#          (wght 200); the `H` shortens monotonically to 650 by wght 900. So the declared
#          cap describes a weight this composite never draws, and both upright sans slots
#          have to be scaled to the `H` they do draw.
#   0.001  KaTeX_Math-Italic's sxHeight: 441 declared against a 442 ink `x`. One unit at
#          1000 upem is the font build's own rounding rather than a disagreement, and
#          preferring the ink here would move the serif composite's Math-Italic slot for
#          no change in what is drawn.
#
# 0.003 sits in the one band -- above the fourth case, below the second and third -- that
# takes the ink where OS/2 misdescribes the outlines and leaves rounding alone.
OS2_INK_TOLERANCE: Final = 0.003
X_HEIGHT_GLYPH: Final = "x"
CAP_HEIGHT_GLYPH: Final = "H"

MetricRow = tuple[float, float, float, float, float]
MetricTable = dict[int, MetricRow]


@dataclass(frozen=True)
class Glyph:
    """One glyph measured in KaTeX's own terms, in em.

    `italic` is the ink overhang past the advance, which is how KaTeX's extractor
    defines the italic correction.
    """

    depth: float
    height: float
    italic: float
    width: float


@dataclass(frozen=True)
class Face:
    """The parts of a woff2 face this tool measures."""

    x_height: float
    cap_height: float
    glyphs: Mapping[int, Glyph]


@dataclass(frozen=True)
class FacePlan:
    """How one KaTeX metric table is rebuilt."""

    katex_face: str
    """Table name in katex.min.js, and the key in the generated asset."""

    katex_font: str
    """The woff2 that face draws from; the Greek factor is derived against it."""

    reading_font: str
    """The woff2 the swapped code points are re-measured from."""

    swapped: tuple[int, ...]
    """Code points the composite family draws from the reading face."""

    greek: tuple[int, ...]
    """Code points the scale factor multiplies."""

    scale: float
    """Frozen Greek scale factor; see the derivation above."""

    reference_glyph: str
    """Glyph whose ink height the factor is measured from."""

    drawn_font: str | None = None
    """The woff2 the composite actually draws this table's Greek with, when it is not
    `katex_font`: both the rows and the factor come from the face that is drawn, so the
    table and the glyphs describe the same outlines."""

    @property
    def scaled_against(self) -> str:
        return self.drawn_font or self.katex_font

    @property
    def greek_source_face(self) -> str:
        """The KaTeX table the Greek rows are copied from before scaling.

        Its own table when the slot draws its own Greek, and the drawn face's table when
        the composite routes the Greek elsewhere: `Main-Italic` is what `\\mathit` is
        laid out from, but the italic slot draws its Greek with KaTeX_Math-Italic, whose
        advances and skews are not Main-Italic's. Scaling Main-Italic's rows would lay
        out one face's Greek for another's glyphs.
        """
        return self.scaled_against.removeprefix("KaTeX_").removesuffix(".woff2")


PT_SERIF_REGULAR: Final = "pt-serif-latin-400-normal.woff2"
PT_SERIF_BOLD: Final = "pt-serif-latin-700-normal.woff2"
PT_SERIF_ITALIC: Final = "pt-serif-latin-400-italic.woff2"
PT_SERIF_BOLD_ITALIC: Final = "pt-serif-latin-700-italic.woff2"

FACE_PLANS: Final = (
    FacePlan(
        katex_face="Main-Regular",
        katex_font="KaTeX_Main-Regular.woff2",
        reading_font=PT_SERIF_REGULAR,
        swapped=LETTERS_AND_DIGITS,
        greek=UPRIGHT_GREEK,
        scale=MAIN_REGULAR_SCALE,
        reference_glyph=CAP_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-Bold",
        katex_font="KaTeX_Main-Bold.woff2",
        reading_font=PT_SERIF_BOLD,
        swapped=LETTERS_AND_DIGITS,
        greek=UPRIGHT_GREEK,
        scale=MAIN_BOLD_SCALE,
        reference_glyph=CAP_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-Italic",
        katex_font="KaTeX_Main-Italic.woff2",
        reading_font=PT_SERIF_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MATH_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
        drawn_font="KaTeX_Math-Italic.woff2",
    ),
    FacePlan(
        katex_face="Main-BoldItalic",
        katex_font="KaTeX_Main-BoldItalic.woff2",
        reading_font=PT_SERIF_BOLD_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MATH_BOLD_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
        drawn_font="KaTeX_Math-BoldItalic.woff2",
    ),
    FacePlan(
        katex_face="Math-Italic",
        katex_font="KaTeX_Math-Italic.woff2",
        reading_font=PT_SERIF_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MATH_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Math-BoldItalic",
        katex_font="KaTeX_Math-BoldItalic.woff2",
        reading_font=PT_SERIF_BOLD_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MATH_BOLD_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
)

SCALE_FACTORS: Final = {plan.katex_face: plan.scale for plan in FACE_PLANS}


# ---- The sans composite ----
#
# `KPress Math Text Sans` draws the same Latin ranges from Source Sans 3, for the sans
# roles of a serif document (a caption, a footnote, a table) and for the reader's sans
# reading face. It needs its own tables because a KaTeX metric table describes one face:
# Source Sans sets `1` on 0.497em where PT Serif sets it on 0.533em, and its digits are
# 0.638em tall where PT Serif's are 0.712em.
#
# A metric table also describes one WEIGHT, and Source Sans is a variable face whose
# advances grow along the axis: across 370-700 the median Latin advance moves 7.1% and
# the widest (`f`) moves 20.5%, while the tallest ink height moves 0.035em and the median
# 0.005em. So the vertical entries -- the ones fractions, scripts and radicals are laid
# out from -- travel, and the widths do not. Each slot of the composite therefore pins
# its drawn weight with a single-valued `font-weight` descriptor, which CSS Fonts 4
# clamps a variable face to, and its table is built at that same weight:
#
#   400  the regular slots. Upstream's `.katex { font: normal 1.21em ... }` resets
#        font-weight, so mathematics in a sans context is already set at 400 whatever
#        weight the words around it carry.
#   650  the bold slots, `--kpress-font-weight-sans-bold`: what "bold" means in every
#        other sans context kpress ships, rather than upstream's 700, which is a step
#        heavier than any bold the document otherwise sets.
#
# The reading fonts below are the static print instances rather than the variable faces
# the screen draws from. They are the same glyphs: instancing the variable face at 400
# and at 650 reproduces every one of the 62 Latin advances of the shipped instance to
# 0.000000em, so one table is true of both, which is what lets the print faces be layered
# into the same composite. See
# docs/project/research/research-2026-09-07-sans-math-face.md.
#
# The Greek factors are derived the same way as the serif set's, against Source Sans's
# own measures. The upright numerators are the drawn `H`, not the declared sCapHeight:
# Source Sans varies its x-height along the weight axis but not its cap height, so OS/2
# reports 660 at every instance while the `H` this composite draws is 656 at 400 and 653
# at 650. OS2_INK_TOLERANCE is what catches that, and the reason it is 0.003 and not the
# 0.02 the serif set alone needed.
#
#   face             Source Sans (per 1000 em)      KaTeX face                factor
#   Main-Regular     `H` 656 at 400               /  KaTeX_Main-Regular 683    0.960
#   Main-Bold        `H` 653 at 650               /  KaTeX_Main-Bold 686       0.952
#   Math-Italic      x 486 at 400 italic          /  KaTeX_Math-Italic 441     1.102
#   Math-BoldItalic  x 494 at 650 italic          /  KaTeX_Math-BoldItalic 452 1.093
#   Main-Italic      as Math-Italic, for the reason the serif set records     1.102
#   Main-BoldItalic  as Math-BoldItalic                                       1.093
#
# The upright factors come out below 1, which the serif set's never did, because KaTeX's
# LATIN `H` is taller than the one Source Sans draws: 683 against 656 at 400, so 4.1%.
# That is what the factor equalizes, and it is a statement about Latin capitals rather
# than about Greek. What it leaves the Greek at is not one number, because Computer
# Modern's Greek capitals are not one height. Measured on the real outlines after the
# 0.960 scale, against the 656 the 400 slot draws: the flat-topped capitals land where
# the factor aims them -- Sigma, Phi and Psi at 99.95% -- while Gamma and Pi sit at
# 99.51%, Xi at 99.07%, and the pointed and round ones overshoot: Omega 103.02%, Theta
# and Upsilon 103.17%, Delta and Lambda 104.78%. That is a 5.7pp spread and no scalar
# removes it, because Computer Modern gives its pointed capitals optical overshoot above
# the cap line and Source Sans's `H` has none. The factor is aimed at the flat-topped
# group, which is the group a reader can line up against a neighbouring Latin capital.
# In fairness to the approach: KaTeX's own table already declares a single height for
# every Greek capital, so this scales a divergence that was there before it.
SANS_REGULAR_WEIGHT: Final = 400
SANS_BOLD_WEIGHT: Final = 650

SANS_MAIN_REGULAR_SCALE: Final = 0.960
SANS_MAIN_BOLD_SCALE: Final = 0.952
SANS_MATH_ITALIC_SCALE: Final = 1.102
SANS_MATH_BOLD_ITALIC_SCALE: Final = 1.093


def sans_font(weight: int, style: str) -> str:
    """The static Source Sans instance a slot is measured from.

    The name is `devtools.instance_sans.instance_name`, spelled out rather than imported
    so this tool keeps reading fonts by file name as it does for PT Serif. The instances
    carry a family of their own (`KPress Print Sans`) because the upstream licence
    reserves the name "Source"; the outlines are the variable face instanced at the
    weight, so measuring them measures the screen face too.
    """
    return f"kpress-print-sans-latin-{weight}-{style}.woff2"


SOURCE_SANS_REGULAR: Final = sans_font(SANS_REGULAR_WEIGHT, "normal")
SOURCE_SANS_BOLD: Final = sans_font(SANS_BOLD_WEIGHT, "normal")
SOURCE_SANS_ITALIC: Final = sans_font(SANS_REGULAR_WEIGHT, "italic")
SOURCE_SANS_BOLD_ITALIC: Final = sans_font(SANS_BOLD_WEIGHT, "italic")

SANS_FACE_PLANS: Final = (
    FacePlan(
        katex_face="Main-Regular",
        katex_font="KaTeX_Main-Regular.woff2",
        reading_font=SOURCE_SANS_REGULAR,
        swapped=LETTERS_AND_DIGITS,
        greek=UPRIGHT_GREEK,
        scale=SANS_MAIN_REGULAR_SCALE,
        reference_glyph=CAP_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-Bold",
        katex_font="KaTeX_Main-Bold.woff2",
        reading_font=SOURCE_SANS_BOLD,
        swapped=LETTERS_AND_DIGITS,
        greek=UPRIGHT_GREEK,
        scale=SANS_MAIN_BOLD_SCALE,
        reference_glyph=CAP_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-Italic",
        katex_font="KaTeX_Main-Italic.woff2",
        reading_font=SOURCE_SANS_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=SANS_MATH_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
        drawn_font="KaTeX_Math-Italic.woff2",
    ),
    FacePlan(
        katex_face="Main-BoldItalic",
        katex_font="KaTeX_Main-BoldItalic.woff2",
        reading_font=SOURCE_SANS_BOLD_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=SANS_MATH_BOLD_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
        drawn_font="KaTeX_Math-BoldItalic.woff2",
    ),
    FacePlan(
        katex_face="Math-Italic",
        katex_font="KaTeX_Math-Italic.woff2",
        reading_font=SOURCE_SANS_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=SANS_MATH_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Math-BoldItalic",
        katex_font="KaTeX_Math-BoldItalic.woff2",
        reading_font=SOURCE_SANS_BOLD_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=SANS_MATH_BOLD_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
)

SANS_SCALE_FACTORS: Final = {plan.katex_face: plan.scale for plan in SANS_FACE_PLANS}


@dataclass(frozen=True)
class Composite:
    """One CSS composite family and the metric tables that lay its glyphs out."""

    key: str | None
    """Where the tables sit in the generated asset: the object's own keys when None,
    a nested object under this name otherwise."""

    family: str
    """The CSS family name, which is how `--check` tells the stylesheet's two sets of
    scaled Greek faces apart: both draw the same KaTeX woff2 at different factors."""

    plans: tuple[FacePlan, ...]

    @property
    def scale_factors(self) -> dict[str, float]:
        return {plan.katex_face: plan.scale for plan in self.plans}


COMPOSITES: Final = (
    Composite(key=None, family="KPress Math Text", plans=FACE_PLANS),
    Composite(key=SANS_KEY, family="KPress Math Text Sans", plans=SANS_FACE_PLANS),
)


class MetricsError(RuntimeError):
    """The inputs are not shaped the way this tool expects."""


# ---- Reading the KaTeX bundle ----

_ENTRY = re.compile(r"(?P<code>\d+):\[(?P<values>[^\]]*)\]")


def parse_katex_table(bundle: str, face: str) -> MetricTable:
    """Read one face's metric table out of the minified KaTeX bundle.

    The tables are object literals with unquoted integer keys and five-number arrays,
    and no nested braces, so a face's table runs from its marker to the next `}`. Any
    departure from that shape is a KaTeX bump this tool has not been reviewed against,
    and raises rather than silently producing a half-right table.
    """
    marker = f'"{face}":{{'
    start = bundle.find(marker)
    if start < 0:
        raise MetricsError(f"{KATEX_BUNDLE.name} has no metric table for {face}")
    if bundle.find(marker, start + 1) >= 0:
        raise MetricsError(f"{KATEX_BUNDLE.name} has more than one metric table for {face}")
    body_start = start + len(marker)
    body_end = bundle.find("}", body_start)
    if body_end < 0:
        raise MetricsError(f"{KATEX_BUNDLE.name} metric table for {face} is unterminated")
    body = bundle[body_start:body_end]

    table: MetricTable = {}
    for match in _ENTRY.finditer(body):
        values = tuple(float(value) for value in match["values"].split(","))
        if len(values) != 5:
            raise MetricsError(
                f"{face} U+{int(match['code']):04X} has {len(values)} values, expected 5"
            )
        table[int(match["code"])] = values

    rebuilt = ",".join(
        f"{code}:[{_katex_row(row)}]" for code, row in sorted(table.items(), key=lambda kv: kv[0])
    )
    if rebuilt != body:
        raise MetricsError(
            f"{KATEX_BUNDLE.name} metric table for {face} is not a flat "
            f"`code:[d,h,i,s,w]` list; the bundle's shape has changed"
        )
    return table


def _katex_row(row: MetricRow) -> str:
    """Re-render one row the way the minified bundle writes it, for the shape check."""
    return ",".join(_katex_number(value) for value in row)


def _katex_number(value: float) -> str:
    """Render a number the way the minified bundle does: no `0` before the point."""
    text = format_number(value)
    if text.startswith("0."):
        return text[1:]
    if text.startswith("-0."):
        return "-" + text[2:]
    return text


# ---- Reading a font ----


def read_face(path: Path) -> Face:
    """Measure one woff2 face: its Latin glyph metrics, x-height and cap height.

    fontTools opens woff2 directly because brotli is installed; brotli is already a
    KPress dependency.
    """
    if not path.is_file():
        raise MetricsError(f"font is missing: {path}")
    font = cast(Any, TTFont(path))
    try:
        units_per_em = float(cast(int, font["head"].unitsPerEm))
        if units_per_em <= 0:
            raise MetricsError(f"{path.name} reports a non-positive unitsPerEm")
        cmap = cast("dict[int, str]", font.getBestCmap())
        glyph_set = font.getGlyphSet()
        horizontal_metrics = font["hmtx"]
        if "OS/2" not in font:
            raise MetricsError(f"{path.name} has no OS/2 table to read its heights from")
        os2 = font["OS/2"]

        glyphs: dict[int, Glyph] = {}
        ink_heights: dict[str, float] = {}
        for code_point, glyph_name in cmap.items():
            pen = BoundsPen(glyph_set)
            glyph_set[glyph_name].draw(pen)
            bounds = cast("tuple[float, float, float, float] | None", pen.bounds)
            advance = float(cast(int, horizontal_metrics[glyph_name][0])) / units_per_em
            if bounds is None:
                glyphs[code_point] = Glyph(depth=0.0, height=0.0, italic=0.0, width=advance)
                continue
            y_min, x_max, y_max = (bounds[index] / units_per_em for index in (1, 2, 3))
            glyphs[code_point] = Glyph(
                depth=max(0.0, -y_min),
                height=max(0.0, y_max),
                italic=max(0.0, x_max - advance),
                width=advance,
            )
            character = chr(code_point)
            if character in (X_HEIGHT_GLYPH, CAP_HEIGHT_GLYPH):
                ink_heights[character] = y_max

        return Face(
            x_height=_vertical_measure(
                float(cast(int, os2.sxHeight)) / units_per_em,
                ink_heights.get(X_HEIGHT_GLYPH),
            ),
            cap_height=_vertical_measure(
                float(cast(int, os2.sCapHeight)) / units_per_em,
                ink_heights.get(CAP_HEIGHT_GLYPH),
            ),
            glyphs=glyphs,
        )
    finally:
        font.close()


def _vertical_measure(declared: float, ink: float | None) -> float:
    """Prefer OS/2, but fall back to the ink height when OS/2 contradicts the outlines.

    Two of the shipped faces need this. KaTeX_Math-BoldItalic declares an sxHeight 80/1000
    above the top of any lowercase glyph it draws, and trusting it would scale the Greek
    the wrong way. Source Sans 3 declares one sCapHeight for its whole weight axis, 4/1000
    above the `H` the 400 slot draws and 7/1000 above the one the 650 slot draws, so
    trusting it would scale both upright sans slots to a cap height drawn at no weight the
    composite pins -- and would scale the bold slot worse than the regular one, since the
    lie grows with weight. A disagreement past OS2_INK_TOLERANCE is therefore resolved in
    favour of what is drawn; the constant's own comment records the four cases it splits.
    """
    if ink is None or abs(declared - ink) <= OS2_INK_TOLERANCE:
        return declared
    return ink


# ---- Building the tables ----


@cache
def read_face_cached(path: Path) -> Face:
    """`read_face`, memoized: several plans share a reading face, and `--check` re-reads."""
    return read_face(path)


def build_tables(plans: Sequence[FacePlan] = FACE_PLANS) -> dict[str, MetricTable]:
    """Rebuild all six metric tables from the bundle and the reading faces."""
    bundle = KATEX_BUNDLE.read_text(encoding="utf-8")
    parsed: dict[str, MetricTable] = {}

    def table_for(face: str) -> MetricTable:
        if face not in parsed:
            parsed[face] = parse_katex_table(bundle, face)
        return parsed[face]

    return {
        plan.katex_face: build_table(
            table_for(plan.katex_face),
            table_for(plan.greek_source_face),
            read_face_cached(READING_FONTS / plan.reading_font),
            plan,
        )
        for plan in plans
    }


def build_table(
    base: MetricTable, greek_source: MetricTable, reading: Face, plan: FacePlan
) -> MetricTable:
    """Swap the reading face's Latin metrics into one table and scale its Greek.

    `greek_source` is the table of the face the composite's slot actually draws Greek
    with (`plan.greek_source_face`), which is `base` for every slot that keeps its own
    Greek and the Math-* table for the two `\\mathit` slots that do not.
    """
    swapped = 0
    table = dict(base)
    for code_point in plan.swapped:
        glyph = reading.glyphs.get(code_point)
        if glyph is None:
            # The reading face does not cover it, so the composite falls back to the
            # KaTeX face for this code point and KaTeX's own entry stays correct.
            continue
        skew = base.get(code_point, (0.0, 0.0, 0.0, 0.0, 0.0))[3]
        table[code_point] = _round_row((glyph.depth, glyph.height, glyph.italic, skew, glyph.width))
        swapped += 1
    if swapped == 0:
        raise MetricsError(f"{plan.reading_font} covers none of {plan.katex_face}'s swapped range")

    for code_point in plan.greek:
        row = greek_source.get(code_point)
        if row is None:
            # The drawn face has no entry here, so the browser falls through to the
            # KaTeX face this slot names after the composite -- which is the face `base`
            # describes. Its own unscaled row is then the right one; leave it alone.
            continue
        table[code_point] = _round_row(cast(MetricRow, tuple(value * plan.scale for value in row)))
    return table


def _round_row(row: MetricRow) -> MetricRow:
    return cast(MetricRow, tuple(round(value, PRECISION) + 0.0 for value in row))


# ---- Deriving and checking the scale factors ----


def derive_scale_factors(plans: Sequence[FacePlan] = FACE_PLANS) -> dict[str, float]:
    """Re-measure the Greek scale factors from the fonts, as the frozen literals were."""
    factors: dict[str, float] = {}
    for plan in plans:
        reading = read_face_cached(READING_FONTS / plan.reading_font)
        katex = read_face_cached(KATEX_FONTS / plan.scaled_against)
        if plan.reference_glyph == CAP_HEIGHT_GLYPH:
            numerator, denominator = reading.cap_height, katex.cap_height
        else:
            numerator, denominator = reading.x_height, katex.x_height
        if denominator <= 0:
            raise MetricsError(f"{plan.scaled_against} reports a non-positive vertical measure")
        factors[plan.katex_face] = round(numerator / denominator, 3)
    return factors


def scale_percentages(composite: Composite = COMPOSITES[0]) -> dict[str, float]:
    """The factors as the percentages the composite's `size-adjust` descriptors carry."""
    return {face: round(factor * 100, 1) for face, factor in composite.scale_factors.items()}


# ---- Rendering the asset ----


def format_number(value: float) -> str:
    """Format one metric value: fixed precision, no trailing zeros, no negative zero."""
    rounded = round(value, PRECISION) + 0.0
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:.{PRECISION}f}".rstrip("0")


def render_asset(tables: Mapping[str, MetricTable], sans_tables: Mapping[str, MetricTable]) -> str:
    """Render the generated JS asset.

    A classic script, not a module: it loads alongside the UMD KaTeX bundle. The object
    is valid JSON so the tests can read it without a JS runtime, and every key is sorted
    and every number formatted the same way so `--check` can compare bytes.

    The serif set is the object's own face keys, for the reading face of prose; the sans
    set is nested under `sans`, for the sans roles and the sans reading face.
    `katex-math-runtime.js` installs the selected set per rendered node.
    """
    body = _face_lines(tables, "  ")
    nested = ",\n".join(
        [*_face_lines(sans_tables, "    "), _scale_line(SANS_SCALE_FACTORS, "    ")]
    )
    body.append(f'  "{SANS_KEY}": {{\n{nested}\n  }}')
    bundle = KATEX_BUNDLE.read_text(encoding="utf-8")
    original = {face: parse_katex_table(bundle, face) for face in tables}
    baseline = ",\n".join(_face_lines(original, "    "))
    body.append(f'  "{KATEX_KEY}": {{\n{baseline}\n  }}')
    body.append(_scale_line(SCALE_FACTORS, "  "))
    return (
        "\n".join([ASSET_HEADER, f"globalThis.{GLOBAL_NAME} = {{", ",\n".join(body), "};"]) + "\n"
    )


def _face_lines(tables: Mapping[str, MetricTable], indent: str) -> list[str]:
    return [f'{indent}"{face}": {{{_render_table(tables[face])}}}' for face in sorted(tables)]


def _scale_line(factors: Mapping[str, float], indent: str) -> str:
    scale = ",".join(f'"{face}":{format_number(factors[face])}' for face in sorted(factors))
    return f'{indent}"{SCALE_KEY}": {{{scale}}}'


def _render_table(table: MetricTable) -> str:
    return ",".join(
        f'"{code}":[{",".join(format_number(value) for value in table[code])}]'
        for code in sorted(table)
    )


def parse_asset(text: str) -> dict[str, Any]:
    """Read a generated asset back, for the tests and for `--check`."""
    prefix = f"globalThis.{GLOBAL_NAME} = "
    start = text.find(prefix)
    if start < 0 or not text.rstrip().endswith(";"):
        raise MetricsError(f"{ASSET_PATH.name} is not a `{prefix.strip()}` assignment")
    return cast("dict[str, Any]", json.loads(text[start + len(prefix) :].rstrip().rstrip(";")))


# ---- Checking ----

_SIZE_ADJUST = re.compile(r"size-adjust\s*:\s*(?P<percentage>[0-9.]+)%")
_FONT_FAMILY = re.compile(r"""font-family\s*:\s*["']?(?P<family>[^"';]+)""")
_SOURCE_FILE = re.compile(r"""src\s*:\s*url\(\s*["']?[^"')]*?(?P<file>[^/"')]+\.woff2)""")
_FONT_FACE_BLOCK = re.compile(r"@font-face\s*\{(?P<body>[^}]*)\}")
_CSS_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)


def check() -> list[str]:
    """Report every way the shipped asset disagrees with its inputs. Empty means clean."""
    problems: list[str] = []
    problems.extend(_check_scale_factors())
    problems.extend(_check_asset())
    problems.extend(_check_face_css())
    problems.extend(_check_bundle_hook())
    return problems


def _check_scale_factors() -> list[str]:
    problems: list[str] = []
    for composite in COMPOSITES:
        frozen = composite.scale_factors
        derived = derive_scale_factors(composite.plans)
        problems.extend(
            f"{composite.family} {face} scale factor is frozen at {frozen[face]} but the "
            f"fonts now give {derived[face]}; review the derivation in "
            f"devtools/katex_text_metrics.py"
            for face in sorted(frozen)
            if derived[face] != frozen[face]
        )
    return problems


def _check_asset() -> list[str]:
    if not ASSET_PATH.is_file():
        return [f"{_relative(ASSET_PATH)} is missing; run `{REGENERATE_COMMAND}`"]
    expected = render_asset(build_tables(FACE_PLANS), build_tables(SANS_FACE_PLANS))
    if ASSET_PATH.read_text(encoding="utf-8") != expected:
        return [
            f"{_relative(ASSET_PATH)} is stale: it is not what its inputs produce. "
            f"Run `{REGENERATE_COMMAND}` to regenerate."
        ]
    return []


def _check_face_css() -> list[str]:
    """Verify each scaled face in a composite carries the factor of the font it draws.

    The stylesheet is written separately from this tool, so the two can drift apart
    silently; the glyphs would then be drawn at one size and laid out at another. So
    the check is per face, not per value: every `@font-face` with a `size-adjust` is
    matched by its family and its `src` file to the plans that draw with that font, and
    the declared percentage must equal theirs. A stylesheet that is missing is a problem
    too.

    Keyed by family as well as by file because the two composites scale the same KaTeX
    woff2 by different factors -- `KaTeX_Main-Regular` reaches PT Serif's cap height at
    102.5% and Source Sans's at 96.0% -- so the file alone no longer names one face.
    """
    if not FACE_CSS_PATH.is_file():
        return [f"{_relative(FACE_CSS_PATH)} is missing; the composite has moved or gone"]
    expected: dict[tuple[str, str], float] = {}
    for composite in COMPOSITES:
        for plan in composite.plans:
            key = (composite.family, plan.scaled_against)
            percentage = round(plan.scale * 100, 1)
            if expected.setdefault(key, percentage) != percentage:
                raise MetricsError(f"{key[1]} is drawn at two factors in {composite.family}")
    css = _CSS_COMMENT.sub("", FACE_CSS_PATH.read_text(encoding="utf-8"))
    problems: list[str] = []
    scaled: list[tuple[str, str]] = []
    for block in _FONT_FACE_BLOCK.finditer(css):
        body = block.group("body")
        adjust = _SIZE_ADJUST.search(body)
        if adjust is None:
            continue
        source = _SOURCE_FILE.search(body)
        family = _FONT_FAMILY.search(body)
        key = (family["family"].strip() if family else "", source["file"] if source else "")
        if key not in expected:
            problems.append(
                f"{_relative(FACE_CSS_PATH)} scales a face this tool does not know: "
                f"{key if any(key) else body.strip()[:60]}"
            )
            continue
        scaled.append(key)
        declared = round(float(adjust["percentage"]), 1)
        if declared != expected[key]:
            problems.append(
                f"{_relative(FACE_CSS_PATH)} scales {key[1]} in {key[0]} by {declared:g}%, but "
                f"its metric tables are scaled by {expected[key]:.1f}%. Run "
                f"`{REGENERATE_COMMAND} --print-scale` and copy the value."
            )
    for key in sorted(expected):
        if scaled.count(key) != 1:
            problems.append(
                f"{_relative(FACE_CSS_PATH)} declares {scaled.count(key)} scaled faces for "
                f"{key[1]} in {key[0]}; the composite needs exactly one"
            )
    return problems


def _check_bundle_hook() -> list[str]:
    """The tables are installed through KaTeX's `__setFontMetrics`, a private export.

    Nothing else pins it: a KaTeX bump that renamed it would leave the faces on and
    the tables off, which the shared runtime turns into a visible revert. This fails
    the check first.
    """
    bundle = KATEX_BUNDLE.read_text(encoding="utf-8")
    if "__setFontMetrics:" not in bundle:
        return [f"{KATEX_BUNDLE.name} no longer exports __setFontMetrics; the hook has moved"]
    return []


def _relative(path: Path) -> str:
    return str(path.relative_to(ROOT))


# ---- CLI ----


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the KaTeX metric tables the math text face lays out from."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="Verify the shipped asset and stylesheet without writing anything.",
    )
    mode.add_argument(
        "--print-scale",
        action="store_true",
        help="Print the Greek scale factor per face, as a size-adjust percentage.",
    )
    args = parser.parse_args(argv)
    try:
        return _run(args.print_scale, args.check)
    except MetricsError as exc:
        print(exc, file=sys.stderr)
        return 1


def _run(print_scale: bool, do_check: bool) -> int:
    if print_scale:
        for composite in COMPOSITES:
            print(f"{composite.family}:")
            for face, percentage in scale_percentages(composite).items():
                print(f"  {face} {percentage:.1f}%")
        return 0

    if do_check:
        problems = check()
        for problem in problems:
            print(problem, file=sys.stderr)
        if problems:
            return 1
        print(f"KaTeX text metrics are current: {_relative(ASSET_PATH)}")
        return 0

    asset = render_asset(build_tables(FACE_PLANS), build_tables(SANS_FACE_PLANS))
    ASSET_PATH.write_text(asset, encoding="utf-8")
    print(f"Wrote {_relative(ASSET_PATH)} ({len(asset.encode('utf-8')):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
