"""Generate the KaTeX metric tables the math text face lays out from.

KaTeX lays out from a metric table baked into its bundle: per face and code point,
``[depth, height, italic, skew, width]`` in em. The math text face draws Latin letters
and digits from the reading face instead of the KaTeX faces, so for those code points
the baked table no longer describes the glyphs on screen, and it also keeps KaTeX's
Greek at a size that reads small beside PT Serif.

This tool rebuilds the six affected tables: swapped code points are re-measured from the
reading face's own outlines, Greek is scaled by a frozen per-face factor, and everything
else is carried over from KaTeX unchanged. The result is written to
``static/katex/katex-text-metrics.js`` as ``globalThis.kpressKatexTextMetrics``;
``katex-init.js`` applies it with ``katex.__setFontMetrics``, which replaces a face's
whole table and has no getter, so each table must be complete.

Run ``python -m devtools.katex_text_metrics`` to regenerate the asset, ``--check`` to
verify the shipped copy still matches its inputs, and ``--print-scale`` to print the
Greek scale factors the composite's ``size-adjust`` descriptors must equal.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Any, Final, cast

from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont

ROOT: Final = Path(__file__).resolve().parents[1]
STATIC: Final = ROOT / "src" / "kpress" / "format" / "static"
KATEX_BUNDLE: Final = STATIC / "katex" / "katex.min.js"
ASSET_PATH: Final = STATIC / "katex" / "katex-text-metrics.js"
FACE_CSS_PATH: Final = STATIC / "katex" / "katex-text-face.css"
READING_FONTS: Final = STATIC / "fonts"
KATEX_FONTS: Final = STATIC / "katex" / "fonts"

REGENERATE_COMMAND: Final = "uv run python -m devtools.katex_text_metrics"

# Public JS contract, mirrored by katex-init.js and the tests.
GLOBAL_NAME: Final = "kpressKatexTextMetrics"
SCALE_KEY: Final = "scale"
ASSET_HEADER: Final = (
    "/* GENERATED by devtools/katex_text_metrics.py — do not edit. Complete KaTeX metric"
    " tables for the faces the math text face swaps; applied by katex-init.js through"
    " katex.__setFontMetrics. */"
)

# KaTeX rounds its own table to five decimals, so five keeps the carried-over entries
# byte-identical to what the bundle ships and gives the re-measured ones the same
# resolution.
PRECISION: Final = 5

# Code points the composite family draws from the reading face.
DIGITS: Final = tuple(range(0x30, 0x3A))
LETTERS: Final = (*range(0x41, 0x5B), *range(0x61, 0x7B))
LETTERS_AND_DIGITS: Final = (*DIGITS, *LETTERS)

# Code points the Greek scale factor multiplies. The upright faces carry capitals only;
# the italic faces carry the lowercase alphabet and its variants as well.
UPRIGHT_GREEK: Final = tuple(range(0x391, 0x3AA))
ITALIC_GREEK: Final = tuple(range(0x370, 0x400))

# ---- Greek scale factors ----
#
# The reading face has no Greek, so KaTeX keeps it, and left alone it sits visibly small
# beside PT Serif. Each affected face is therefore scaled to the reading face's own
# vertical measure -- italic Greek to its x-height, upright capitals to its cap height --
# and every metric value in the Greek ranges is multiplied by the same factor so KaTeX
# lays out what the browser draws.
#
# Derived once from OS/2, rounded to three decimals, and frozen here as literals because
# the `size-adjust` descriptors in katex-text-face.css must equal them exactly. Nothing
# recomputes them at run time: `--print-scale` prints them, and `--check` re-derives them
# from the fonts and fails if a font bump has moved one.
#
#   face             reading face (per 1000 em)     KaTeX face                factor
#   Main-Regular     PT Serif cap 700             /  KaTeX_Main-Regular 683    1.025
#   Main-Bold        PT Serif cap 700             /  KaTeX_Main-Bold 686       1.020
#   Main-Italic      PT Serif Italic x 507        /  KaTeX_Main-Italic 442     1.147
#   Main-BoldItalic  PT Serif Bold Italic x 509   /  KaTeX_Main-BoldItalic 451 1.129
#   Math-Italic      PT Serif Italic x 507        /  KaTeX_Math-Italic 441     1.150
#   Math-BoldItalic  PT Serif Bold Italic x 509   /  KaTeX_Math-BoldItalic 452 1.126
#
# KaTeX_Math-BoldItalic is the one face whose OS/2 sxHeight is not its x-height: the
# table says 532 while every lowercase glyph in the face tops out at 452, and 532 would
# shrink the Greek instead of growing it. `_vertical_measure` cross-checks OS/2 against
# the ink height of the reference glyph and prefers the ink when the two disagree by more
# than OS2_INK_TOLERANCE, which is where 452 comes from.
MAIN_REGULAR_SCALE: Final = 1.025
MAIN_BOLD_SCALE: Final = 1.020
MAIN_ITALIC_SCALE: Final = 1.147
MAIN_BOLD_ITALIC_SCALE: Final = 1.129
MATH_ITALIC_SCALE: Final = 1.150
MATH_BOLD_ITALIC_SCALE: Final = 1.126

# Ink-versus-OS/2 disagreement, in em, past which the ink height wins.
OS2_INK_TOLERANCE: Final = 0.02
X_HEIGHT_GLYPH: Final = "x"
CAP_HEIGHT_GLYPH: Final = "H"

MetricRow = tuple[float, float, float, float, float]
MetricTable = dict[int, MetricRow]


@dataclass(frozen=True)
class Glyph:
    """One glyph measured in KaTeX's own terms, in em.

    `italic` is the ink overhang past the advance, which is how KaTeX's extractor
    defines the italic correction.
    """

    depth: float
    height: float
    italic: float
    width: float


@dataclass(frozen=True)
class Face:
    """The parts of a woff2 face this tool measures."""

    x_height: float
    cap_height: float
    glyphs: Mapping[int, Glyph]


@dataclass(frozen=True)
class FacePlan:
    """How one KaTeX metric table is rebuilt."""

    katex_face: str
    """Table name in katex.min.js, and the key in the generated asset."""

    katex_font: str
    """The woff2 that face draws from; the Greek factor is derived against it."""

    reading_font: str
    """The woff2 the swapped code points are re-measured from."""

    swapped: tuple[int, ...]
    """Code points the composite family draws from the reading face."""

    greek: tuple[int, ...]
    """Code points the scale factor multiplies."""

    scale: float
    """Frozen Greek scale factor; see the derivation above."""

    reference_glyph: str
    """Glyph whose ink height the factor is measured from."""


PT_SERIF_REGULAR: Final = "pt-serif-latin-400-normal.woff2"
PT_SERIF_BOLD: Final = "pt-serif-latin-700-normal.woff2"
PT_SERIF_ITALIC: Final = "pt-serif-latin-400-italic.woff2"
PT_SERIF_BOLD_ITALIC: Final = "pt-serif-latin-700-italic.woff2"

FACE_PLANS: Final = (
    FacePlan(
        katex_face="Main-Regular",
        katex_font="KaTeX_Main-Regular.woff2",
        reading_font=PT_SERIF_REGULAR,
        swapped=LETTERS_AND_DIGITS,
        greek=UPRIGHT_GREEK,
        scale=MAIN_REGULAR_SCALE,
        reference_glyph=CAP_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-Bold",
        katex_font="KaTeX_Main-Bold.woff2",
        reading_font=PT_SERIF_BOLD,
        swapped=LETTERS_AND_DIGITS,
        greek=UPRIGHT_GREEK,
        scale=MAIN_BOLD_SCALE,
        reference_glyph=CAP_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-Italic",
        katex_font="KaTeX_Main-Italic.woff2",
        reading_font=PT_SERIF_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MAIN_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Main-BoldItalic",
        katex_font="KaTeX_Main-BoldItalic.woff2",
        reading_font=PT_SERIF_BOLD_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MAIN_BOLD_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Math-Italic",
        katex_font="KaTeX_Math-Italic.woff2",
        reading_font=PT_SERIF_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MATH_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
    FacePlan(
        katex_face="Math-BoldItalic",
        katex_font="KaTeX_Math-BoldItalic.woff2",
        reading_font=PT_SERIF_BOLD_ITALIC,
        swapped=LETTERS,
        greek=ITALIC_GREEK,
        scale=MATH_BOLD_ITALIC_SCALE,
        reference_glyph=X_HEIGHT_GLYPH,
    ),
)

SCALE_FACTORS: Final = {plan.katex_face: plan.scale for plan in FACE_PLANS}


class MetricsError(RuntimeError):
    """The inputs are not shaped the way this tool expects."""


# ---- Reading the KaTeX bundle ----

_ENTRY = re.compile(r"(?P<code>\d+):\[(?P<values>[^\]]*)\]")


def parse_katex_table(bundle: str, face: str) -> MetricTable:
    """Read one face's metric table out of the minified KaTeX bundle.

    The tables are object literals with unquoted integer keys and five-number arrays,
    and no nested braces, so a face's table runs from its marker to the next `}`. Any
    departure from that shape is a KaTeX bump this tool has not been reviewed against,
    and raises rather than silently producing a half-right table.
    """
    marker = f'"{face}":{{'
    start = bundle.find(marker)
    if start < 0:
        raise MetricsError(f"{KATEX_BUNDLE.name} has no metric table for {face}")
    if bundle.find(marker, start + 1) >= 0:
        raise MetricsError(f"{KATEX_BUNDLE.name} has more than one metric table for {face}")
    body_start = start + len(marker)
    body_end = bundle.find("}", body_start)
    if body_end < 0:
        raise MetricsError(f"{KATEX_BUNDLE.name} metric table for {face} is unterminated")
    body = bundle[body_start:body_end]

    table: MetricTable = {}
    for match in _ENTRY.finditer(body):
        values = tuple(float(value) for value in match["values"].split(","))
        if len(values) != 5:
            raise MetricsError(
                f"{face} U+{int(match['code']):04X} has {len(values)} values, expected 5"
            )
        table[int(match["code"])] = values

    rebuilt = ",".join(
        f"{code}:[{_katex_row(row)}]" for code, row in sorted(table.items(), key=lambda kv: kv[0])
    )
    if rebuilt != body:
        raise MetricsError(
            f"{KATEX_BUNDLE.name} metric table for {face} is not a flat "
            f"`code:[d,h,i,s,w]` list; the bundle's shape has changed"
        )
    return table


def _katex_row(row: MetricRow) -> str:
    """Re-render one row the way the minified bundle writes it, for the shape check."""
    return ",".join(_katex_number(value) for value in row)


def _katex_number(value: float) -> str:
    """Render a number the way the minified bundle does: no `0` before the point."""
    text = format_number(value)
    if text.startswith("0."):
        return text[1:]
    if text.startswith("-0."):
        return "-" + text[2:]
    return text


# ---- Reading a font ----


def read_face(path: Path) -> Face:
    """Measure one woff2 face: its Latin glyph metrics, x-height and cap height.

    fontTools opens woff2 directly because brotli is installed; brotli is already a
    KPress dependency.
    """
    if not path.is_file():
        raise MetricsError(f"font is missing: {path}")
    font = cast(Any, TTFont(path))
    try:
        units_per_em = float(cast(int, font["head"].unitsPerEm))
        if units_per_em <= 0:
            raise MetricsError(f"{path.name} reports a non-positive unitsPerEm")
        cmap = cast("dict[int, str]", font.getBestCmap())
        glyph_set = font.getGlyphSet()
        horizontal_metrics = font["hmtx"]
        os2 = font["OS/2"]

        glyphs: dict[int, Glyph] = {}
        ink_heights: dict[str, float] = {}
        for code_point, glyph_name in cmap.items():
            pen = BoundsPen(glyph_set)
            glyph_set[glyph_name].draw(pen)
            bounds = cast("tuple[float, float, float, float] | None", pen.bounds)
            advance = float(cast(int, horizontal_metrics[glyph_name][0])) / units_per_em
            if bounds is None:
                glyphs[code_point] = Glyph(depth=0.0, height=0.0, italic=0.0, width=advance)
                continue
            y_min, x_max, y_max = (bounds[index] / units_per_em for index in (1, 2, 3))
            glyphs[code_point] = Glyph(
                depth=max(0.0, -y_min),
                height=max(0.0, y_max),
                italic=max(0.0, x_max - advance),
                width=advance,
            )
            character = chr(code_point)
            if character in (X_HEIGHT_GLYPH, CAP_HEIGHT_GLYPH):
                ink_heights[character] = y_max

        return Face(
            x_height=_vertical_measure(
                float(cast(int, os2.sxHeight)) / units_per_em,
                ink_heights.get(X_HEIGHT_GLYPH),
            ),
            cap_height=_vertical_measure(
                float(cast(int, os2.sCapHeight)) / units_per_em,
                ink_heights.get(CAP_HEIGHT_GLYPH),
            ),
            glyphs=glyphs,
        )
    finally:
        font.close()


def _vertical_measure(declared: float, ink: float | None) -> float:
    """Prefer OS/2, but fall back to the ink height when OS/2 contradicts the outlines.

    KaTeX_Math-BoldItalic declares an sxHeight 80/1000 above the top of any lowercase
    glyph it draws. Trusting it there would scale the Greek the wrong way, so a
    disagreement past OS2_INK_TOLERANCE is resolved in favour of what is drawn. See the
    scale-factor derivation above.
    """
    if ink is None or abs(declared - ink) <= OS2_INK_TOLERANCE:
        return declared
    return ink


# ---- Building the tables ----


@cache
def read_face_cached(path: Path) -> Face:
    """`read_face`, memoized: several plans share a reading face, and `--check` re-reads."""
    return read_face(path)


def build_tables() -> dict[str, MetricTable]:
    """Rebuild all six metric tables from the bundle and the reading faces."""
    bundle = KATEX_BUNDLE.read_text(encoding="utf-8")
    return {
        plan.katex_face: build_table(
            parse_katex_table(bundle, plan.katex_face),
            read_face_cached(READING_FONTS / plan.reading_font),
            plan,
        )
        for plan in FACE_PLANS
    }


def build_table(base: MetricTable, reading: Face, plan: FacePlan) -> MetricTable:
    """Swap the reading face's Latin metrics into one table and scale its Greek."""
    swapped = 0
    table = dict(base)
    for code_point in plan.swapped:
        glyph = reading.glyphs.get(code_point)
        if glyph is None:
            # The reading face does not cover it, so the composite falls back to the
            # KaTeX face for this code point and KaTeX's own entry stays correct.
            continue
        skew = base.get(code_point, (0.0, 0.0, 0.0, 0.0, 0.0))[3]
        table[code_point] = _round_row((glyph.depth, glyph.height, glyph.italic, skew, glyph.width))
        swapped += 1
    if swapped == 0:
        raise MetricsError(f"{plan.reading_font} covers none of {plan.katex_face}'s swapped range")

    for code_point in plan.greek:
        row = base.get(code_point)
        if row is None:
            continue
        table[code_point] = _round_row(cast(MetricRow, tuple(value * plan.scale for value in row)))
    return table


def _round_row(row: MetricRow) -> MetricRow:
    return cast(MetricRow, tuple(round(value, PRECISION) + 0.0 for value in row))


# ---- Deriving and checking the scale factors ----


def derive_scale_factors() -> dict[str, float]:
    """Re-measure the Greek scale factors from the fonts, as the frozen literals were."""
    factors: dict[str, float] = {}
    for plan in FACE_PLANS:
        reading = read_face_cached(READING_FONTS / plan.reading_font)
        katex = read_face_cached(KATEX_FONTS / plan.katex_font)
        if plan.reference_glyph == CAP_HEIGHT_GLYPH:
            numerator, denominator = reading.cap_height, katex.cap_height
        else:
            numerator, denominator = reading.x_height, katex.x_height
        if denominator <= 0:
            raise MetricsError(f"{plan.katex_font} reports a non-positive vertical measure")
        factors[plan.katex_face] = round(numerator / denominator, 3)
    return factors


def scale_percentages() -> dict[str, float]:
    """The factors as the percentages the composite's `size-adjust` descriptors carry."""
    return {face: round(factor * 100, 1) for face, factor in SCALE_FACTORS.items()}


# ---- Rendering the asset ----


def format_number(value: float) -> str:
    """Format one metric value: fixed precision, no trailing zeros, no negative zero."""
    rounded = round(value, PRECISION) + 0.0
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:.{PRECISION}f}".rstrip("0")


def render_asset(tables: Mapping[str, MetricTable]) -> str:
    """Render the generated JS asset.

    A classic script, not a module: it loads alongside the UMD KaTeX bundle. The object
    is valid JSON so the tests can read it without a JS runtime, and every key is sorted
    and every number formatted the same way so `--check` can compare bytes.
    """
    lines = [ASSET_HEADER, f"globalThis.{GLOBAL_NAME} = {{"]
    body = [f'  "{face}": {{{_render_table(tables[face])}}}' for face in sorted(tables)]
    scale = ",".join(
        f'"{face}":{format_number(SCALE_FACTORS[face])}' for face in sorted(SCALE_FACTORS)
    )
    body.append(f'  "{SCALE_KEY}": {{{scale}}}')
    lines.append(",\n".join(body))
    lines.append("};")
    return "\n".join(lines) + "\n"


def _render_table(table: MetricTable) -> str:
    return ",".join(
        f'"{code}":[{",".join(format_number(value) for value in table[code])}]'
        for code in sorted(table)
    )


def parse_asset(text: str) -> dict[str, Any]:
    """Read a generated asset back, for the tests and for `--check`."""
    prefix = f"globalThis.{GLOBAL_NAME} = "
    start = text.find(prefix)
    if start < 0 or not text.rstrip().endswith(";"):
        raise MetricsError(f"{ASSET_PATH.name} is not a `{prefix.strip()}` assignment")
    return cast("dict[str, Any]", json.loads(text[start + len(prefix) :].rstrip().rstrip(";")))


# ---- Checking ----

_SIZE_ADJUST = re.compile(r"size-adjust\s*:\s*(?P<percentage>[0-9.]+)%")


def check() -> list[str]:
    """Report every way the shipped asset disagrees with its inputs. Empty means clean."""
    problems: list[str] = []
    problems.extend(_check_scale_factors())
    problems.extend(_check_asset())
    problems.extend(_check_face_css())
    return problems


def _check_scale_factors() -> list[str]:
    derived = derive_scale_factors()
    return [
        f"{face} scale factor is frozen at {SCALE_FACTORS[face]} but the fonts now give "
        f"{derived[face]}; review the derivation in devtools/katex_text_metrics.py"
        for face in sorted(SCALE_FACTORS)
        if derived[face] != SCALE_FACTORS[face]
    ]


def _check_asset() -> list[str]:
    if not ASSET_PATH.is_file():
        return [f"{_relative(ASSET_PATH)} is missing; run `{REGENERATE_COMMAND}`"]
    if ASSET_PATH.read_text(encoding="utf-8") != render_asset(build_tables()):
        return [
            f"{_relative(ASSET_PATH)} is stale: it is not what its inputs produce. "
            f"Run `{REGENERATE_COMMAND}` to regenerate."
        ]
    return []


def _check_face_css() -> list[str]:
    """Verify the composite's `size-adjust` descriptors match the frozen factors.

    The stylesheet is written separately from this tool, so the two can drift apart
    silently; the glyphs would then be drawn at one size and laid out at another. The
    file is optional so this tool can land before it does.
    """
    if not FACE_CSS_PATH.is_file():
        return []
    percentages = scale_percentages()
    allowed = set(percentages.values())
    expected = ", ".join(f"{face} {value:.1f}%" for face, value in percentages.items())
    css = FACE_CSS_PATH.read_text(encoding="utf-8")
    declared = _unique(round(float(match["percentage"]), 1) for match in _SIZE_ADJUST.finditer(css))
    return [
        f"{_relative(FACE_CSS_PATH)} declares `size-adjust: {value:g}%`, which is not one of "
        f"the generated scale factors ({expected}). Run `{REGENERATE_COMMAND} --print-scale`."
        for value in declared
        if value not in allowed
    ]


def _unique(values: Iterable[float]) -> Sequence[float]:
    return list(dict.fromkeys(values))


def _relative(path: Path) -> str:
    return str(path.relative_to(ROOT))


# ---- CLI ----


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the KaTeX metric tables the math text face lays out from."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the shipped asset and stylesheet without writing anything.",
    )
    parser.add_argument(
        "--print-scale",
        action="store_true",
        help="Print the Greek scale factor per face, as a size-adjust percentage.",
    )
    args = parser.parse_args(argv)

    if args.print_scale:
        for face, percentage in scale_percentages().items():
            print(f"{face} {percentage:.1f}%")
        return 0

    if args.check:
        problems = check()
        for problem in problems:
            print(problem, file=sys.stderr)
        if problems:
            return 1
        print(f"KaTeX text metrics are current: {_relative(ASSET_PATH)}")
        return 0

    asset = render_asset(build_tables())
    ASSET_PATH.write_text(asset, encoding="utf-8")
    print(f"Wrote {_relative(ASSET_PATH)} ({len(asset.encode('utf-8')):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
